- name: System Info Check
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Get OS info
      command: cat /etc/os-release
      register: os_info

    - name: Get total disk size
      shell: lsblk -b -o NAME,TYPE,SIZE | awk '$2=="disk"{print $1,$3}'
      register: disk_info
      changed_when: false
      ignore_errors: yes

    - name: Get root partition usage
      command: df -h /
      register: root_usage

    - name: Get RAM info
      command: free -h
      register: ram_info

    - name: Get hostname
      command: hostname
      register: hostname_info

    - name: Get IP address
      command: hostname -I
      register: ip_info

    - name: Print all info
      debug:
        msg:
          - "OS: {{ os_info.stdout }}"
          - "Disk: {{ disk_info.stdout }}"
          - "/ Usage: {{ root_usage.stdout }}"
          - "RAM: {{ ram_info.stdout }}"
          - "Hostname: {{ hostname_info.stdout }}"
          - "IP: {{ ip_info.stdout }}"
