- name: Create ansible user with sudo and no password
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Create user ansible
      user:
        name: ansible
        shell: /bin/bash
        create_home: yes
        groups: sudo
        append: yes
        password: "{{ 'helloworld' | password_hash('sha512') }}"

    - name: Allow ansible user passwordless sudo
      copy:
        dest: /etc/sudoers.d/ansible
        content: "ansible ALL=(ALL) NOPASSWD:ALL\n"
        mode: '0440'
